aws:
  region: us-west-2

tracing_priorities:
  - Message Bus with Amazon SQS
  - Conditional Branches
  - Exception Handling Blocks
  - Function Entry/Exit Points
  - Complex Algorithm Sections
  - Performance-Critical Code Paths
  - State Changes
  - External Resource Interactions

formatter:
  class:
    name: Jinja2JsonToMarkdownFormatter
  module:
    name: jinja2_json_to_markdown_formatter
  template:
    name: jinja2_json_to_markdown_formatter.jinja2
    path: source_analyzer/formatters

formatter_default_jinja2:
  class:
    name: Jinja2JsonToMarkdownFormatter
  module:
    name: jinja2_json_to_markdown_formatter
  template:
    name: jinja2_json_to_markdown_formatter.jinja2
    path: source_analyzer/formatters

formatter_meta_jinja:
  class:
    name: Jinja2JsonToMarkdownFormatter
  module:
    name: jinja2_json_to_markdown_formatter
  template:
    name: jinja2_json_to_markdown_formatter_meta.jinja2
    path: source_analyzer/formatters

formatter_coded:
  class:
    name: CodedJsonToMarkdownFormatter
  module:
    name: coded_json_to_markdown_formatter

ai_model:
  max_llm_tries: 1
  retry_delay: 4
  temperature: 0.0
  custom:
    max_tokens: 40960
  class:
    name: AnthropicClaude3Sonnet20240229V1
  module:
    name: anthropic_claude_3_sonnet_20240229_v1_0
  model_stop:
    reasons:
      max_tokens:
        - max_tokens
      valid:
        - end_turn

ai_model_keep_anthropic_claude3_sonnet:
  #
  # This section is not used, but is a holding area for
  # specific model configuration
  #
  max_llm_tries: 2
  retry_delay: 4
  temperature: 0.0
  custom:
    max_tokens: 2048
  class:
    name: AnthropicClaude3Sonnet20240229V1
  module:
    name: anthropic_claude_3_sonnet_20240229_v1_0
  model_stop:
    reasons:
      valid:
        - end_turn

ai_model_keep_meta_llama:
  #
  # This section is not used, but is a holding area for
  # specific model configuration
  #
  max_llm_tries: 2
  retry_delay: 4
  temperature: 0.0
  custom:
    max_gen_len: 6134
  class:
    name: MetaLlama323bInstructV1
  module:
    name: meta_llama3_2_3b_instruct_v1_0
  model_stop:
    reasons:
      valid:
        - end_turn
